# Site settings
title: Enxec
description: 'Business Card Page'
url: 'https://enxec.businesscard.nbyte.kr'
baseurl: ''
profilepic: '/images/enxec.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '44a86f330f.js'

author:
  name: 'enxec'
  email: dev21mo@gmail.com
#  mastodon: tzuehlke@mstdn.social
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  enxec
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
